package com.example.inscreveai.models.enums;

public enum MovementEventEnum {

    CHARGE_CREATED,
    CHARGE_DISPLAYED,
    CHARGE_REFUTED,
    PAYMENT_REFUSED,
    PAYMENT_AUTHORIZED,
    PAID_CHARGE,
    RETURNS_CHARGE,
    CANCELLED_CHARGE,
    OPEN_CHARGE,
    CANCELLED_MONTHLY_FEE,
    CREATED_MONTHLY_FEE,
    PAUSED_MONTHLY_FEE,
    REACTIVATED_MONTHLY_FEE,
    TERMINATED_MONTHLY_FEE


}
